export const healthNames: Record<string, string> = {
  service: "服务状态",
  service_name: "服务名称",
  version: "OpenVPN 版本",
  started_at: "服务启动时间",
  last_result: "最近服务结果",
  vpn_network: "VPN 网段",
  server_config: "主配置权限检查",
  routes_config: "路由文件检查",
  crl: "CRL 文件检查",
  preflight: "配置结构预检查",
  status_updated_at: "状态文件更新时间",
  ipv4_forward: "IPv4 Forward",
  nat: "NAT 规则存在性",
  forward: "FORWARD 规则存在性",
  firewall_note: "防火墙检查说明",
  fake: "演示模式",
  mode: "运行模式",
  certificates: "PKI 证书统计",
  certificate_error: "PKI 统计错误",
  routes_error: "路由统计错误",
  applied_routes: "服务器分流规则数",
};
